# Shotgun Pipeline Toolkit configuration file
# this file was automatically created

host: https://tank.shotgunstudio.com
api_script: com_shotgunstudio_aau
api_key: dab32e19322a723f301aec67086e9c9913ee4b8f
http_proxy: null

# End of file.
