# Shotgun Pipeline Toolkit configuration file
# This file was automatically created by setup_project
# This file reflects the paths in the primary pipeline
# configuration defined for this project.

Windows: '\\180net1\mnt$\software\shotgun\sX_Goldenman'
Darwin: '/Volumes/mnt$/software/shotgun/sX_Goldenman'
Linux: '/Volumes/mnt$/software/shotgun/sX_Goldenman'

# End of file.
